version: "3.4"
services:
  rasa:
    image: rasa-server-okteto:latest
    build: "./"
    volumes:
      - /app/actions
      - /app/data
    command: bash -c "rm -rf .rasa/* && rasa train && rasa run --enable-api --cors \"*\" -p 5006"
    working_dir: /app
    ports:
      - "5006:5006"
    networks:
      - all

  rasa-actions:
    image: rasa-server-okteto:latest
    build: "./"
    volumes:
      - /app/actions
    command: bash -c "rasa run actions"
    working_dir: /app
    ports:
      - "5055:5055"
    networks:
      - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
