version: "3.4"
services:
  rasa:
    image: rasa-server-okteto:latest
    build: "./"
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    command: bash -c "rm -rf .rasa/* && rasa train && rasa run --enable-api --cors \"*\" --debug -p 5006"
    working_dir: /app
    ports:
      - "5006:5006"
    networks:
      - all
    env_file:
      - .env
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      RASA_URL: ${RASA_URL}

  rasa-actions:
    image: rasa-server-okteto:latest
    build: "./"
    volumes:
      - ./actions:/app/actions
    command: bash -c "rasa run actions --debug"
    working_dir: /app
    ports:
      - "5055:5055"
    networks:
      - all
    env_file:
      - .env
    environment:
      GRAMMAR_TOOL_KEY: ${GRAMMAR_TOOL_KEY}
      TRANSLATE_KEY: ${TRANSLATE_KEY}
      SLACK_TOKEN: ${SLACK_TOKEN}

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
