version: "3.4"
services:
  rasa:
    image: rasa-server-okteto:latest
    build: "./"
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    command: bash -c "rm -rf .rasa/* && rasa train && MAX_NUMBER_OF_PREDICTIONS=30 rasa run --enable-api --cors \"*\" --debug -p 5006"
    working_dir: /app
    ports:
      - "5006:5006"
    networks:
      - all
    env_file:
      - .env
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      RASA_URL: ${RASA_URL}
      MONGO_DB_URL: ${MONGO_DB_URL}
      DB_NAME: ${DB_NAME}
      USERNAME: ${USERNAME}
      PSWD: ${PSWD}
      RASA_ACTIONS_URL: "https://rasa-actions-ben-dp1-dp4-paulkeller94.cloud.okteto.net/webhook"

  rasa-two:
    image: rasa-server-okteto-two:latest
    build: "./"
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    command: bash -c "rm -rf .rasa/* && rasa train && MAX_NUMBER_OF_PREDICTIONS=30 rasa run --enable-api --cors \"*\" --debug -p 5007"
    working_dir: /app
    ports:
      - "5007:5007"
    networks:
      - all
    env_file:
      - .env
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN_TWO}
      SLACK_CHANNEL: ${SLACK_CHANNEL_TWO}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET_TWO}
      RASA_URL: ${RASA_URL}
      MONGO_DB_URL: ${MONGO_DB_URL}
      DB_NAME: ${DB_NAME}
      USERNAME: ${USERNAME}
      PSWD: ${PSWD}
      RASA_ACTIONS_URL: "https://rasa-actions-two-ben-dp1-dp4-paulkeller94.cloud.okteto.net/webhook"

  rasa-three:
    image: rasa-server-okteto-three:latest
    build: "./"
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    command: bash -c "rm -rf .rasa/* && rasa train && MAX_NUMBER_OF_PREDICTIONS=30 rasa run --enable-api --cors \"*\" --debug -p 5008"
    working_dir: /app
    ports:
      - "5008:5008"
    networks:
      - all
    env_file:
      - .env
    environment:
      SLACK_TOKEN: ${SLACK_TOKEN_THREE}
      SLACK_CHANNEL: ${SLACK_CHANNEL_THREE}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET_THREE}
      RASA_URL: ${RASA_URL}
      MONGO_DB_URL: ${MONGO_DB_URL}
      DB_NAME: ${DB_NAME}
      USERNAME: ${USERNAME}
      PSWD: ${PSWD}
      RASA_ACTIONS_URL: "https://rasa-actions-three-ben-dp1-dp4-paulkeller94.cloud.okteto.net/webhook"

  rasa-actions:
    image: rasa-server-okteto:latest
    build: "./"
    volumes:
      - ./actions:/app/actions
    command: bash -c "rasa run actions --debug"
    working_dir: /app
    ports:
      - "5055:5055"
    networks:
      - all
    env_file:
      - .env
    environment:
      GRAMMAR_TOOL_KEY: ${GRAMMAR_TOOL_KEY}
      TRANSLATE_KEY: ${TRANSLATE_KEY}
      SLACK_TOKEN: ${SLACK_TOKEN}

  rasa-actions-two:
    image: rasa-server-okteto-two:latest
    build: "./"
    volumes:
      - ./actions:/app/actions
    command: bash -c "rasa run actions --debug"
    working_dir: /app
    ports:
      - "5056:5056"
    networks:
      - all
    env_file:
      - .env
    environment:
      GRAMMAR_TOOL_KEY: ${GRAMMAR_TOOL_KEY}
      TRANSLATE_KEY: ${TRANSLATE_KEY}
      SLACK_TOKEN: ${SLACK_TOKEN_TWO}

  rasa-actions-three:
    image: rasa-server-okteto-three:latest
    build: "./"
    volumes:
      - ./actions:/app/actions
    command: bash -c "rasa run actions --debug"
    working_dir: /app
    ports:
      - "5057:5057"
    networks:
      - all
    env_file:
      - .env
    environment:
      GRAMMAR_TOOL_KEY: ${GRAMMAR_TOOL_KEY}
      TRANSLATE_KEY: ${TRANSLATE_KEY}
      SLACK_TOKEN: ${SLACK_TOKEN_THREE}

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
